"""候选 Profile API 集成测试（任务 10.6）。

覆盖：
- ``POST /api/admin/profiles/candidates`` 接收 envelope，返回 201 + 候选响应
- 缺失字段 envelope → 400
- ``GET /api/admin/profiles/candidates`` 只返回候选记录
- ``POST /api/admin/profiles/candidates/{id}/approve`` 翻转 enabled / 去前缀
- ``POST /api/admin/profiles/candidates/{id}/reject`` 返回 204；再次访问 404
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.api.admin_profiles import router as admin_profiles_router
from app.core.database import get_db
from app.core.exceptions import register_exception_handlers
from app.models.document_profile import DocumentProfile
from app.services.profile_candidate_service import (
    CANDIDATE_DESCRIPTION_PREFIX,
    CANDIDATE_METADATA_KEY,
)


# ─── helpers ─────────────────────────────────────────────────────────


def _scalar(value):
    r = MagicMock()
    r.scalar_one_or_none.return_value = value
    return r


def _scalars_all(values):
    r = MagicMock()
    scalars = MagicMock()
    scalars.all.return_value = list(values)
    r.scalars.return_value = scalars
    return r


def _make_envelope(
    *,
    name: str = "auto-generated-pdf-2p",
    description: str | None = "Automatically generated by Universal Parser",
    status: str = "pending_approval",
    evidence: dict | None = None,
) -> dict:
    return {
        "profile": {
            "name": name,
            "description": description,
            "priority": 0,
            "enabled": False,
            "match_rules": {
                "filename_regex": [],
                "content_regex": [],
                "min_content_match_count": 1,
            },
            "heading_rules": [
                {"pattern": r"^[一二三四五六七八九十]+、", "level": 1, "strip_pattern": False},
            ],
            "boilerplate": {
                "detection_mode": "both",
                "statistical_threshold": 0.5,
                "manual_patterns": [],
            },
            "tables": {
                "cross_page_merge": True,
                "row_level_chunking": False,
                "collapse_merged_cells": "describe",
            },
            "chunking": {
                "min_tokens": 256,
                "max_tokens": 800,
                "overlap_tokens": 80,
                "respect_heading_level": 1,
                "protect_patterns": [],
            },
            "domain_dictionary_id": None,
        },
        "metadata": {
            "status": status,
            "source": "universal_parser",
            "evidence": evidence
            or {
                "page_count": 2,
                "heading_count": 2,
                "table_count": 0,
                "boilerplate_candidates": 0,
                "avg_block_chars": 38.5,
            },
        },
    }


def _build_candidate_orm(
    *,
    name: str = "auto-generated-pdf-2p",
    version: int = 1,
    description: str = f"{CANDIDATE_DESCRIPTION_PREFIX}LLM 推断",
    profile_id: uuid.UUID | None = None,
) -> DocumentProfile:
    p = DocumentProfile(
        name=name,
        description=description,
        priority=0,
        enabled=False,
        match_rules={
            "filename_regex": [],
            "content_regex": [],
            "min_content_match_count": 1,
            CANDIDATE_METADATA_KEY: {
                "status": "pending_approval",
                "source": "universal_parser",
                "evidence": {
                    "page_count": 2,
                    "heading_count": 2,
                    "table_count": 0,
                    "boilerplate_candidates": 0,
                    "avg_block_chars": 38.5,
                },
            },
        },
        heading_rules=[],
        boilerplate={"detection_mode": "both", "statistical_threshold": 0.5, "manual_patterns": []},
        tables={"cross_page_merge": True, "row_level_chunking": False, "collapse_merged_cells": "describe"},
        chunking={"min_tokens": 256, "max_tokens": 800, "overlap_tokens": 80, "respect_heading_level": 1, "protect_patterns": []},
        version=version,
    )
    p.id = profile_id or uuid.uuid4()
    p.created_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
    p.updated_at = p.created_at
    p.domain_dictionary_id = None
    return p


# ─── fixtures ────────────────────────────────────────────────────────


@pytest.fixture
def mock_db():
    db = AsyncMock()
    db.add = MagicMock()
    db.flush = AsyncMock()
    db.delete = AsyncMock()
    db.commit = AsyncMock()
    db.rollback = AsyncMock()

    async def fake_refresh(obj):
        if getattr(obj, "id", None) is None:
            obj.id = uuid.uuid4()
        if getattr(obj, "created_at", None) is None:
            obj.created_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
        if getattr(obj, "updated_at", None) is None:
            obj.updated_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
        if getattr(obj, "version", None) is None:
            obj.version = 1
        if getattr(obj, "domain_dictionary_id", None) is None:
            obj.domain_dictionary_id = None

    db.refresh = AsyncMock(side_effect=fake_refresh)
    return db


@pytest.fixture
def app(mock_db):
    application = FastAPI()
    register_exception_handlers(application)
    application.include_router(admin_profiles_router)

    async def _override_get_db():
        yield mock_db

    application.dependency_overrides[get_db] = _override_get_db
    return application


@pytest.fixture
def client(app):
    return TestClient(app)


@pytest.fixture(autouse=True)
def stub_admin_user(monkeypatch):
    admin_uid = uuid.uuid4()
    monkeypatch.setattr(
        "app.services.profile_candidate_service.get_admin_user_id",
        AsyncMock(return_value=admin_uid),
    )
    monkeypatch.setattr(
        "app.api.admin_profiles._get_admin_user_id",
        AsyncMock(return_value=admin_uid),
    )
    return admin_uid


# ─── POST /candidates ────────────────────────────────────────────────


class TestCreateCandidate:
    def test_create_returns_201_and_marks_disabled(self, client, mock_db):
        # 唯一性查询（save_candidate 内部）→ 没冲突
        mock_db.execute = AsyncMock(return_value=_scalar(None))

        response = client.post(
            "/api/admin/profiles/candidates",
            json=_make_envelope(),
        )
        assert response.status_code == 201, response.text
        body = response.json()

        # ── envelope 形态 ──
        assert set(body.keys()) == {"profile", "metadata"}
        prof = body["profile"]
        assert prof["enabled"] is False
        assert prof["description"].startswith(CANDIDATE_DESCRIPTION_PREFIX)
        assert prof["name"] == "auto-generated-pdf-2p"

        meta = body["metadata"]
        assert meta["status"] == "pending_approval"
        assert meta["source"] == "universal_parser"
        assert meta["evidence"]["page_count"] == 2

    def test_create_with_name_collision_appends_suffix(self, client, mock_db):
        existing = _build_candidate_orm(name="auto-generated-pdf-2p")
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(existing),  # base 冲突
                _scalar(None),  # -1 可用
            ]
        )

        response = client.post(
            "/api/admin/profiles/candidates",
            json=_make_envelope(name="auto-generated-pdf-2p"),
        )
        assert response.status_code == 201
        assert response.json()["profile"]["name"] == "auto-generated-pdf-2p-1"

    def test_create_with_invalid_status_returns_400(self, client, mock_db):
        # 形态合法（pydantic 通过），但服务层校验 status
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        response = client.post(
            "/api/admin/profiles/candidates",
            json=_make_envelope(status="approved"),
        )
        assert response.status_code == 400
        assert "status" in response.text

    def test_create_missing_metadata_returns_422(self, client, mock_db):
        # Pydantic 层就拒绝
        bad = _make_envelope()
        bad.pop("metadata")
        response = client.post("/api/admin/profiles/candidates", json=bad)
        assert response.status_code == 422

    def test_create_missing_profile_name_returns_422(self, client, mock_db):
        bad = _make_envelope()
        bad["profile"]["name"] = ""
        response = client.post("/api/admin/profiles/candidates", json=bad)
        assert response.status_code == 422


# ─── GET /candidates ─────────────────────────────────────────────────


class TestListCandidates:
    def test_list_returns_only_candidates(self, client, mock_db):
        candidate = _build_candidate_orm()
        # list_candidates 内部连续 2 次 execute
        mock_db.execute = AsyncMock(
            side_effect=[_scalars_all([candidate]), _scalars_all([candidate])]
        )

        response = client.get("/api/admin/profiles/candidates")
        assert response.status_code == 200, response.text
        body = response.json()
        assert body["total"] == 1
        assert len(body["candidates"]) == 1
        item = body["candidates"][0]
        assert item["profile"]["enabled"] is False
        assert item["profile"]["description"].startswith(CANDIDATE_DESCRIPTION_PREFIX)
        assert item["metadata"]["status"] == "pending_approval"
        assert item["metadata"]["evidence"]["page_count"] == 2

    def test_list_empty(self, client, mock_db):
        mock_db.execute = AsyncMock(
            side_effect=[_scalars_all([]), _scalars_all([])]
        )
        response = client.get("/api/admin/profiles/candidates")
        assert response.status_code == 200
        assert response.json() == {"candidates": [], "total": 0}


# ─── POST /candidates/{id}/approve ───────────────────────────────────


class TestApproveCandidate:
    def test_approve_flips_enabled_and_strips_prefix(self, client, mock_db):
        candidate = _build_candidate_orm()
        # approve 内部依次：fetch by id → canonical 名字检查
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(None)]
        )

        response = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/approve",
            json={"change_note": "looks good"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert body["enabled"] is True
        assert not (body["description"] or "").startswith(CANDIDATE_DESCRIPTION_PREFIX)
        assert CANDIDATE_METADATA_KEY not in body["match_rules"]
        # 版本自增
        assert body["version"] == 2

    def test_approve_with_priority_and_disabled(self, client, mock_db):
        candidate = _build_candidate_orm()
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(None)]
        )

        response = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/approve",
            json={"priority": 7, "enabled": False},
        )
        assert response.status_code == 200
        body = response.json()
        assert body["priority"] == 7
        assert body["enabled"] is False  # 显式 disable 仍允许（管理员意愿优先）

    def test_approve_non_candidate_returns_404(self, client, mock_db):
        not_candidate = DocumentProfile(
            name="real",
            description="not candidate",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        not_candidate.id = uuid.uuid4()
        mock_db.execute = AsyncMock(return_value=_scalar(not_candidate))

        response = client.post(
            f"/api/admin/profiles/candidates/{not_candidate.id}/approve",
            json={},
        )
        assert response.status_code == 404

    def test_approve_with_canonical_collision_returns_409(self, client, mock_db):
        candidate = _build_candidate_orm(name="auto-generated-pdf-2p-1")
        rival = DocumentProfile(
            name="auto-generated-pdf-2p",
            description="real profile",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=4,
        )
        rival.id = uuid.uuid4()
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(rival)]
        )

        response = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/approve",
            json={},
        )
        assert response.status_code == 409


# ─── POST /candidates/{id}/reject ────────────────────────────────────


class TestRejectCandidate:
    def test_reject_returns_204(self, client, mock_db):
        candidate = _build_candidate_orm()
        mock_db.execute = AsyncMock(return_value=_scalar(candidate))

        response = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/reject"
        )
        assert response.status_code == 204
        mock_db.delete.assert_awaited_once_with(candidate)

    def test_reject_then_get_returns_404(self, client, mock_db):
        # 第一次 POST reject：找到候选，删除
        candidate = _build_candidate_orm()

        # 后续 fetch_by_id 返回 None
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(candidate),  # reject 内部 fetch
                _scalar(None),  # 第二次 reject 找不到
            ]
        )

        first = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/reject"
        )
        assert first.status_code == 204

        second = client.post(
            f"/api/admin/profiles/candidates/{candidate.id}/reject"
        )
        assert second.status_code == 404

    def test_reject_non_candidate_returns_404(self, client, mock_db):
        not_candidate = DocumentProfile(
            name="real",
            description="not candidate",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        not_candidate.id = uuid.uuid4()
        mock_db.execute = AsyncMock(return_value=_scalar(not_candidate))

        response = client.post(
            f"/api/admin/profiles/candidates/{not_candidate.id}/reject"
        )
        assert response.status_code == 404
