"""候选 Profile 服务层单元测试（任务 10.6）。

覆盖：
- ``save_candidate`` 正常路径 / envelope 校验失败 / 名字冲突自动加 ``-N`` 后缀
- ``list_candidates`` 只返回候选记录，按创建时间倒序
- ``approve_candidate`` 转正流程：清掉前缀 + sentinel、自增版本、写版本快照
- ``approve_candidate`` 拒绝非候选 / 名字还原后冲突
- ``reject_candidate`` 删除 + 非候选 404 等价于 ValueError
- ``get_candidate_metadata`` round-trip
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.models.document_profile import DocumentProfile
from app.models.profile_version import ProfileVersion
from app.services.profile_candidate_service import (
    CANDIDATE_DESCRIPTION_PREFIX,
    CANDIDATE_METADATA_KEY,
    approve_candidate,
    get_candidate_metadata,
    is_candidate_profile,
    list_candidates,
    reject_candidate,
    save_candidate,
)


# ─── helpers ─────────────────────────────────────────────────────────


def _scalar(value):
    r = MagicMock()
    r.scalar_one_or_none.return_value = value
    return r


def _scalars_all(values):
    r = MagicMock()
    scalars = MagicMock()
    scalars.all.return_value = list(values)
    r.scalars.return_value = scalars
    return r


def _make_envelope(
    *,
    name: str = "auto-generated-pdf-3p",
    description: str | None = "Automatically generated by Universal Parser",
    priority: int = 0,
    heading_rules: list[dict] | None = None,
    boilerplate: dict | None = None,
    chunking: dict | None = None,
    tables: dict | None = None,
    match_rules: dict | None = None,
    evidence: dict | None = None,
    status: str = "pending_approval",
) -> dict:
    """构造一个与 ``UniversalParser.suggest_profile`` 同形态的候选 envelope。"""
    return {
        "profile": {
            "name": name,
            "description": description,
            "priority": priority,
            "enabled": False,
            "match_rules": match_rules
            or {"filename_regex": [], "content_regex": [], "min_content_match_count": 1},
            "heading_rules": heading_rules or [],
            "boilerplate": boilerplate
            or {
                "detection_mode": "both",
                "statistical_threshold": 0.5,
                "manual_patterns": [],
            },
            "tables": tables
            or {
                "cross_page_merge": True,
                "row_level_chunking": False,
                "collapse_merged_cells": "describe",
            },
            "chunking": chunking
            or {
                "min_tokens": 256,
                "max_tokens": 800,
                "overlap_tokens": 80,
                "respect_heading_level": 1,
                "protect_patterns": [],
            },
            "domain_dictionary_id": None,
        },
        "metadata": {
            "status": status,
            "source": "universal_parser",
            "evidence": evidence
            or {
                "page_count": 3,
                "heading_count": 2,
                "table_count": 0,
                "boilerplate_candidates": 0,
                "avg_block_chars": 42.0,
            },
        },
    }


@pytest.fixture
def mock_db():
    db = AsyncMock()
    db.add = MagicMock()
    db.flush = AsyncMock()
    db.delete = AsyncMock()
    db.commit = AsyncMock()
    db.rollback = AsyncMock()

    async def fake_refresh(obj):
        if getattr(obj, "id", None) is None:
            obj.id = uuid.uuid4()
        if getattr(obj, "created_at", None) is None:
            obj.created_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
        if getattr(obj, "updated_at", None) is None:
            obj.updated_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
        if getattr(obj, "version", None) is None:
            obj.version = 1
        if getattr(obj, "domain_dictionary_id", None) is None:
            obj.domain_dictionary_id = None

    db.refresh = AsyncMock(side_effect=fake_refresh)
    return db


# ─── save_candidate ───────────────────────────────────────────────────


class TestSaveCandidateHappyPath:
    """``save_candidate`` 正常路径。"""

    @pytest.mark.asyncio
    async def test_persists_candidate_with_disabled_and_prefix(self, mock_db):
        # 唯一性查询返回 None
        mock_db.execute = AsyncMock(return_value=_scalar(None))

        envelope = _make_envelope()
        profile = await save_candidate(mock_db, envelope)

        assert profile.enabled is False
        assert profile.description.startswith(CANDIDATE_DESCRIPTION_PREFIX)
        # 元数据 sentinel 写入了 match_rules
        meta = profile.match_rules.get(CANDIDATE_METADATA_KEY)
        assert meta is not None
        assert meta["status"] == "pending_approval"
        assert meta["source"] == "universal_parser"
        assert meta["evidence"]["page_count"] == 3
        # 原始 match_rules 字段仍然存在
        assert profile.match_rules["filename_regex"] == []
        assert profile.match_rules["min_content_match_count"] == 1

        mock_db.add.assert_called_once()
        added = mock_db.add.call_args.args[0]
        assert isinstance(added, DocumentProfile)
        assert added is profile

    @pytest.mark.asyncio
    async def test_get_candidate_metadata_round_trip(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        envelope = _make_envelope()
        profile = await save_candidate(mock_db, envelope)

        meta = get_candidate_metadata(profile)
        assert meta is not None
        assert meta["status"] == "pending_approval"
        assert meta["evidence"]["page_count"] == 3

        # 非候选 Profile（手动构造 enabled=True）
        normal = DocumentProfile(
            name="normal",
            description="usual profile",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        assert get_candidate_metadata(normal) is None
        assert is_candidate_profile(normal) is False

    @pytest.mark.asyncio
    async def test_existing_prefix_in_description_not_doubled(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        envelope = _make_envelope(
            description=f"{CANDIDATE_DESCRIPTION_PREFIX}LLM 推断",
        )
        profile = await save_candidate(mock_db, envelope)
        assert profile.description.count(CANDIDATE_DESCRIPTION_PREFIX) == 1


class TestSaveCandidateValidation:
    """``save_candidate`` envelope 形态校验。"""

    @pytest.mark.asyncio
    async def test_missing_profile_key(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        with pytest.raises(ValueError, match="profile"):
            await save_candidate(mock_db, {"metadata": {"status": "pending_approval"}})

    @pytest.mark.asyncio
    async def test_missing_metadata_key(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        with pytest.raises(ValueError, match="metadata"):
            await save_candidate(mock_db, {"profile": {"name": "x"}})

    @pytest.mark.asyncio
    async def test_wrong_status_value(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        bad = _make_envelope(status="approved")
        with pytest.raises(ValueError, match="status"):
            await save_candidate(mock_db, bad)

    @pytest.mark.asyncio
    async def test_missing_profile_name(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        bad = _make_envelope()
        bad["profile"]["name"] = ""
        with pytest.raises(ValueError, match="name"):
            await save_candidate(mock_db, bad)

    @pytest.mark.asyncio
    async def test_non_dict_envelope(self, mock_db):
        with pytest.raises(ValueError, match="envelope"):
            await save_candidate(mock_db, "not a dict")  # type: ignore[arg-type]


class TestSaveCandidateNameCollision:
    """``save_candidate`` 在名字冲突时自动追加 ``-N`` 后缀。"""

    @pytest.mark.asyncio
    async def test_collision_appends_suffix(self, mock_db):
        # 第一次查询：name 冲突；第二次查询：name-1 可用
        existing = DocumentProfile(
            name="auto-generated-pdf-3p",
            description=None,
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        existing.id = uuid.uuid4()
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(existing),  # name conflict
                _scalar(None),  # name-1 available
            ]
        )

        envelope = _make_envelope(name="auto-generated-pdf-3p")
        profile = await save_candidate(mock_db, envelope)
        assert profile.name == "auto-generated-pdf-3p-1"

    @pytest.mark.asyncio
    async def test_multiple_collisions_increment(self, mock_db):
        existing = DocumentProfile(
            name="placeholder",
            description=None,
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        existing.id = uuid.uuid4()
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(existing),  # base name
                _scalar(existing),  # -1
                _scalar(existing),  # -2
                _scalar(None),  # -3 available
            ]
        )
        envelope = _make_envelope(name="auto-generated-pdf-3p")
        profile = await save_candidate(mock_db, envelope)
        assert profile.name == "auto-generated-pdf-3p-3"


# ─── list_candidates ──────────────────────────────────────────────────


class TestListCandidates:
    @pytest.mark.asyncio
    async def test_returns_only_candidates(self, mock_db):
        candidate = DocumentProfile(
            name="auto-generated-pdf-2p",
            description=f"{CANDIDATE_DESCRIPTION_PREFIX}LLM 推断",
            priority=0,
            enabled=False,
            match_rules={CANDIDATE_METADATA_KEY: {"status": "pending_approval", "source": "universal_parser", "evidence": {}}},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        candidate.id = uuid.uuid4()
        candidate.created_at = datetime(2024, 6, 1, tzinfo=timezone.utc)
        candidate.updated_at = candidate.created_at

        # list_candidates 内部连续两次 execute（count → page）
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalars_all([candidate]),
                _scalars_all([candidate]),
            ]
        )

        profiles, total = await list_candidates(mock_db)
        assert total == 1
        assert len(profiles) == 1
        assert profiles[0].name == "auto-generated-pdf-2p"
        assert is_candidate_profile(profiles[0])

    @pytest.mark.asyncio
    async def test_empty_when_no_candidates(self, mock_db):
        mock_db.execute = AsyncMock(
            side_effect=[_scalars_all([]), _scalars_all([])]
        )
        profiles, total = await list_candidates(mock_db)
        assert profiles == []
        assert total == 0


# ─── approve_candidate ────────────────────────────────────────────────


def _build_candidate_orm(
    *,
    name: str = "auto-generated-pdf-3p",
    version: int = 1,
    description: str = f"{CANDIDATE_DESCRIPTION_PREFIX}LLM 推断",
) -> DocumentProfile:
    p = DocumentProfile(
        name=name,
        description=description,
        priority=0,
        enabled=False,
        match_rules={
            "filename_regex": [],
            "content_regex": [],
            "min_content_match_count": 1,
            CANDIDATE_METADATA_KEY: {
                "status": "pending_approval",
                "source": "universal_parser",
                "evidence": {"page_count": 3},
            },
        },
        heading_rules=[],
        boilerplate={},
        tables={},
        chunking={},
        version=version,
    )
    p.id = uuid.uuid4()
    p.created_at = datetime(2024, 1, 1, tzinfo=timezone.utc)
    p.updated_at = p.created_at
    p.domain_dictionary_id = None
    return p


class TestApproveCandidate:
    @pytest.fixture(autouse=True)
    def _patch_admin_user(self, monkeypatch):
        admin_uid = uuid.uuid4()
        monkeypatch.setattr(
            "app.services.profile_candidate_service.get_admin_user_id",
            AsyncMock(return_value=admin_uid),
        )
        return admin_uid

    @pytest.mark.asyncio
    async def test_approve_strips_marker_and_increments_version(self, mock_db):
        candidate = _build_candidate_orm(version=1)
        # 先 fetch by id → 候选；接着检查 canonical 名字冲突 → 没有冲突
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(None)]
        )

        approved = await approve_candidate(mock_db, candidate.id, change_note="ok")

        assert approved.enabled is True
        assert not (approved.description or "").startswith(CANDIDATE_DESCRIPTION_PREFIX)
        assert CANDIDATE_METADATA_KEY not in approved.match_rules
        assert approved.version == 2

        # 写入了一条 ProfileVersion 快照
        added = [c.args[0] for c in mock_db.add.call_args_list]
        versions = [o for o in added if isinstance(o, ProfileVersion)]
        assert len(versions) == 1
        snap = versions[0]
        assert snap.profile_id == candidate.id
        assert snap.version == 2
        assert snap.change_note == "ok"

    @pytest.mark.asyncio
    async def test_approve_with_priority_override(self, mock_db):
        candidate = _build_candidate_orm()
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(None)]
        )

        approved = await approve_candidate(
            mock_db, candidate.id, priority_override=42
        )
        assert approved.priority == 42

    @pytest.mark.asyncio
    async def test_approve_strips_numeric_suffix_when_canonical_free(self, mock_db):
        candidate = _build_candidate_orm(name="auto-generated-pdf-3p-1")
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(candidate),  # fetch by id
                _scalar(None),  # base 名字 ``auto-generated-pdf-3p`` 是空的
                _scalar(None),  # 最终 canonical 名字检查
            ]
        )

        approved = await approve_candidate(mock_db, candidate.id)
        assert approved.name == "auto-generated-pdf-3p"

    @pytest.mark.asyncio
    async def test_approve_keeps_suffix_when_canonical_taken_by_other_candidate(
        self, mock_db
    ):
        candidate = _build_candidate_orm(name="auto-generated-pdf-3p-1")
        sibling = _build_candidate_orm(name="auto-generated-pdf-3p")  # 另一个候选
        mock_db.execute = AsyncMock(
            side_effect=[
                _scalar(candidate),
                _scalar(sibling),  # canonical 撞上了，但是个候选
                _scalar(None),  # 最终 candidate.name 检查
            ]
        )

        approved = await approve_candidate(mock_db, candidate.id)
        # canonical 还原失败，保留原名
        assert approved.name == "auto-generated-pdf-3p-1"

    @pytest.mark.asyncio
    async def test_approve_rejects_when_canonical_collides_with_real_profile(
        self, mock_db
    ):
        candidate = _build_candidate_orm(name="auto-generated-pdf-3p-1")
        # 真实非候选 Profile 占用了 canonical 名字
        rival = DocumentProfile(
            name="auto-generated-pdf-3p",
            description="real profile",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=3,
        )
        rival.id = uuid.uuid4()
        mock_db.execute = AsyncMock(
            side_effect=[_scalar(candidate), _scalar(rival)]
        )

        with pytest.raises(ValueError, match="collide"):
            await approve_candidate(mock_db, candidate.id)

    @pytest.mark.asyncio
    async def test_approve_rejects_non_candidate(self, mock_db):
        not_candidate = DocumentProfile(
            name="real",
            description="not a candidate",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        not_candidate.id = uuid.uuid4()
        mock_db.execute = AsyncMock(return_value=_scalar(not_candidate))

        with pytest.raises(ValueError, match="not a pending candidate"):
            await approve_candidate(mock_db, not_candidate.id)

    @pytest.mark.asyncio
    async def test_approve_rejects_when_profile_not_found(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        with pytest.raises(ValueError, match="not found"):
            await approve_candidate(mock_db, uuid.uuid4())


# ─── reject_candidate ─────────────────────────────────────────────────


class TestRejectCandidate:
    @pytest.mark.asyncio
    async def test_reject_deletes_candidate(self, mock_db):
        candidate = _build_candidate_orm()
        mock_db.execute = AsyncMock(return_value=_scalar(candidate))

        await reject_candidate(mock_db, candidate.id)
        mock_db.delete.assert_awaited_once_with(candidate)

    @pytest.mark.asyncio
    async def test_reject_non_candidate_raises(self, mock_db):
        not_candidate = DocumentProfile(
            name="real",
            description="not a candidate",
            priority=0,
            enabled=True,
            match_rules={},
            heading_rules=[],
            boilerplate={},
            tables={},
            chunking={},
            version=1,
        )
        not_candidate.id = uuid.uuid4()
        mock_db.execute = AsyncMock(return_value=_scalar(not_candidate))

        with pytest.raises(ValueError, match="not a pending candidate"):
            await reject_candidate(mock_db, not_candidate.id)
        mock_db.delete.assert_not_called()

    @pytest.mark.asyncio
    async def test_reject_missing_raises(self, mock_db):
        mock_db.execute = AsyncMock(return_value=_scalar(None))
        with pytest.raises(ValueError, match="not found"):
            await reject_candidate(mock_db, uuid.uuid4())


# ─── description prefix idempotence ──────────────────────────────────


def test_candidate_description_prefix_constant():
    """常量必须以方括号开头并以单空格结尾，确保 ``startswith`` 检查稳定。"""
    assert CANDIDATE_DESCRIPTION_PREFIX.startswith("[")
    assert CANDIDATE_DESCRIPTION_PREFIX.endswith(" ")
    assert re.match(r"^\[CANDIDATE\] $", CANDIDATE_DESCRIPTION_PREFIX)
